// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OBM_Project.Data;

namespace OBM_Project.Migrations
{
    [DbContext(typeof(OBM_ProjectContext))]
    [Migration("20200731182223_Primeira_Migration")]
    partial class Primeira_Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OBM_Project.Models.Necessidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("TB_Necessidade");
                });

            modelBuilder.Entity("OBM_Project.Models.Orcamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("NecesssidadeId");

                    b.Property<string>("Observacao");

                    b.Property<int?>("SubTipoServicoId");

                    b.Property<int?>("TipoServicoId");

                    b.HasKey("Id");

                    b.HasIndex("NecesssidadeId");

                    b.HasIndex("SubTipoServicoId");

                    b.HasIndex("TipoServicoId");

                    b.ToTable("TB_Orcamentos");
                });

            modelBuilder.Entity("OBM_Project.Models.SubTipoServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("TB_SubTipoServico");
                });

            modelBuilder.Entity("OBM_Project.Models.TipoServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("TB_TipoServico");
                });

            modelBuilder.Entity("OBM_Project.Models.Orcamento", b =>
                {
                    b.HasOne("OBM_Project.Models.Necessidade", "Necesssidade")
                        .WithMany()
                        .HasForeignKey("NecesssidadeId");

                    b.HasOne("OBM_Project.Models.SubTipoServico", "SubTipoServico")
                        .WithMany()
                        .HasForeignKey("SubTipoServicoId");

                    b.HasOne("OBM_Project.Models.TipoServico", "TipoServico")
                        .WithMany()
                        .HasForeignKey("TipoServicoId");
                });
#pragma warning restore 612, 618
        }
    }
}
